# Generated by Django 3.2.9 on 2021-11-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_time', models.IntegerField()),
                ('win_resp', models.IntegerField(choices=[('n', 'nizni'), ('v', 'verhni')])),
            ],
        ),
    ]
