# Generated by Django 3.2.9 on 2021-11-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlelog',
            name='win_resp',
            field=models.CharField(choices=[('n', 'nizni'), ('v', 'verhni')], max_length=1),
        ),
    ]
