# Generated by Django 3.2.9 on 2021-11-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
