# Generated by Django 3.2.9 on 2021-11-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_tank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='lvl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
