# Generated by Django 3.2.9 on 2021-11-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211109_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('battle_count', models.IntegerField()),
                ('wins_count', models.IntegerField()),
                ('tanks', models.ManyToManyField(related_name='players', to='mainapp.Tank')),
            ],
        ),
    ]
