# Generated by Django 3.2.9 on 2021-11-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tank',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='mainapp.tankproperties'),
        ),
    ]
