# Generated by Django 3.2.9 on 2021-12-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211129_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tankproperties',
            options={'verbose_name': 'ТТХ', 'verbose_name_plural': 'ТТХ'},
        ),
        migrations.RemoveField(
            model_name='tank',
            name='property',
        ),
        migrations.AddField(
            model_name='tankproperties',
            name='tank',
            field=models.OneToOneField(error_messages={'null': 'ну так а танк то какой?'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='mainapp.tank'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='lvl',
            field=models.IntegerField(choices=[(None, 'не известно'), ('до 2023 года', ((1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X'))), ('после 2023 года', ((11, 'XI'), (12, 'XII'), (13, 'XIII')))], default=8, verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='name',
            field=models.CharField(error_messages={'unique': 'танк с таким названием уже есть'}, help_text='\n        <img src="https://s8.travelask.ru/system/images/files/000/042/524/wysiwyg_jpg/frog-photography-27__880.jpg?1486386835" width=100px>\n        ', max_length=50, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='type',
            field=models.IntegerField(choices=[(0, 'ЛТ'), (1, 'ПТ'), (2, 'СТ'), (3, 'ТТ'), (4, 'САУ'), (5, 'ПТСАУ')], null=True, verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='tankproperties',
            name='hp',
            field=models.IntegerField(verbose_name='количество ХП'),
        ),
        migrations.AlterField(
            model_name='tankproperties',
            name='speed',
            field=models.IntegerField(help_text='укажыте пожалуйста адекватные цыфры, а не как у колёснуков', verbose_name='скорость'),
        ),
    ]
