# Generated by Django 3.2.9 on 2021-12-27 18:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211202_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AddField(
            model_name='tank',
            name='photo',
            field=models.ImageField(null=True, upload_to='tanks/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='battle_count',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество боёв'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins_count',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='\n            это значение должно быть положительным целым числом\n            ')], verbose_name='количество побед'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='name',
            field=models.CharField(error_messages={'unique': 'танк с таким названием уже есть'}, help_text='\n        <img src="https://s8.travelask.ru/system/images/files/000/042/524/wysiwyg_jpg/frog-photography-27__880.jpg?1486386835" width=100px>\n        ', max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(10, message='\n            название не должно превышать 10 символов\n            ')], verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tankproperties',
            name='tank',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='mainapp.tank'),
        ),
    ]
