# Generated by Django 3.2.9 on 2021-12-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20211227_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tanks',
            field=models.ManyToManyField(blank=True, related_name='players', to='mainapp.Tank'),
        ),
    ]
