# Generated by Django 3.2.9 on 2021-12-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_player_tanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(null=True, upload_to='players/', verbose_name='фото'),
        ),
    ]
